[package]
name = "clashofclans-api"
version = "0.0.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
urlencoding = "2.1"

[dev-dependencies]
serde_json = "1.0"
